# Generated by Django 5.2 on 2025-05-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookingline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gcash', 'GCash')], max_length=50),
        ),
    ]
