# Generated by Django 5.2 on 2025-05-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='notes',
        ),
    ]
