# Generated by Django 5.2 on 2025-05-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_receipt_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['available_time']},
        ),
    ]
